spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bookhub_identity}
    username: ${DB_USERNAME:bookhub}
    password: ${DB_PASSWORD:bookhub}
  jpa:
    show-sql: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoint:
    health:
      show-details: always
