services:
  postgres:
    image: postgres:16-alpine
    container_name: bookhub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookhub-network

volumes:
  postgres_data:
    driver: local

networks:
  bookhub-network:
    driver: bridge