spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookhub
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection.isolation: 2
        cache.use_second_level_cache: false
        cache.use_query_cache: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.notificationhub: DEBUG