minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.8'
  - '@angular-devkit/core@22.0.8'
  - '@angular-devkit/schematics@22.0.8'
  - '@angular/build@22.0.8'
  - '@angular/cli@22.0.8'
  - '@schematics/angular@22.0.8'
