spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      resourceserver:

jwt:
  issuer: test-issuer
  audience: test-audience



catalog:
  service:
    base-url: http://localhost:19999

identity:
  service:
    url: http://localhost:18081

service:
  client-id: test-library-client
  client-secret: test-library-secret

server:
  port: 0

management:
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,prometheus
